In [3]:
import os
os.getcwd()

'c:\\Users\\whimp\\Downloads\\Advanced Process Controls\\Homework'

In [5]:
import pandas as pd

df = pd.read_csv("meter_Hw4/data/Meter_A.txt", sep="\t")
df.head()

,0.841498715000000,1.00936652600000,0.993816009000000,8.46980516700000,10.2787266700000,10.0377595000000,8.50136466700000,8.58172616700000,10.2477633300000,10.0588216700000,...,32.4511733300000,34.5686850000000,33.0826833300000,36.7220050000000,36.9694033300000,36.0758466700000,36.0514316700000,35.1741550000000,32.7294900000000,1
0,0.842250,1.006584,0.996605,7.531891,9.139924,8.951618,7.612213,7.623325,9.106345,8.945142,...,32.428385,34.441732,33.081055,36.687825,36.933595,36.054688,35.979818,34.847005,32.731122,1
1,0.840723,1.011647,0.998152,6.641699,7.975464,7.857692,6.593117,6.681572,7.964596,7.814698,...,32.428385,34.275715,33.113605,36.661785,36.873370,36.002605,35.963542,34.689128,32.771810,1
2,0.841119,1.017807,0.996812,5.687524,6.824334,6.689885,5.615428,5.763315,6.801051,6.686639,...,32.485350,34.080403,33.170573,36.673177,36.811525,35.974935,35.955403,34.500328,32.849935,1
3,0.840358,1.016534,0.996221,5.660385,6.829560,6.675628,5.623977,5.736818,6.813453,6.672377,...,32.503255,34.122720,33.164062,36.673177,36.826173,35.996095,35.968425,34.474283,32.853190,1
4,0.838901,1.014557,0.995404,5.646000,6.830224,6.660216,5.630102,5.712871,6.813999,6.693988,...,32.495117,34.103192,33.168945,36.666668,36.827800,35.997722,35.958658,34.488932,32.849935,1

In [6]:
import pandas as pd

df = pd.read_csv("meter_Hw4/data/Meter_A.txt", sep="\t", header=None)
df.columns = [f"x{i}" for i in range(df.shape[1])]
df.head()

,x0,x1,x2,x3,x4,x5,x6,x7,x8,x9,...,x27,x28,x29,x30,x31,x32,x33,x34,x35,x36
0,0.841499,1.009367,0.993816,8.469805,10.278727,10.037759,8.501365,8.581726,10.247763,10.058822,...,32.451173,34.568685,33.082683,36.722005,36.969403,36.075847,36.051432,35.174155,32.729490,1
1,0.842250,1.006584,0.996605,7.531891,9.139924,8.951618,7.612213,7.623325,9.106345,8.945142,...,32.428385,34.441732,33.081055,36.687825,36.933595,36.054688,35.979818,34.847005,32.731122,1
2,0.840723,1.011647,0.998152,6.641699,7.975464,7.857692,6.593117,6.681572,7.964596,7.814698,...,32.428385,34.275715,33.113605,36.661785,36.873370,36.002605,35.963542,34.689128,32.771810,1
3,0.841119,1.017807,0.996812,5.687524,6.824334,6.689885,5.615428,5.763315,6.801051,6.686639,...,32.485350,34.080403,33.170573,36.673177,36.811525,35.974935,35.955403,34.500328,32.849935,1
4,0.840358,1.016534,0.996221,5.660385,6.829560,6.675628,5.623977,5.736818,6.813453,6.672377,...,32.503255,34.122720,33.164062,36.673177,36.826173,35.996095,35.968425,34.474283,32.853190,1

In [7]:
df.shape
df.isna().sum().sum()   # total missing values
df.describe().T.head()

,count,mean,std,min,25%,50%,75%,max
x0,87.0,0.824482,0.018146,0.790194,0.809688,0.833332,0.840179,0.847096
x1,87.0,1.012743,0.007418,0.997058,1.008405,1.013437,1.018409,1.028315
x2,87.0,0.997459,0.002046,0.993241,0.995865,0.997486,0.998824,1.002573
x3,87.0,4.682436,1.800595,1.781262,2.855605,5.361665,5.665208,8.469805
x4,87.0,5.754454,2.224012,2.247824,3.454327,6.796140,6.836397,10.287437

In [8]:
df["x36"].value_counts().head(10)

x36
2    52
1    35
Name: count, dtype: int64

In [9]:
X = df.drop(columns=["x36"])
y = df["x36"]

X.shape, y.shape

((87, 36), (87,))

In [10]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

X_train.shape, X_test.shape

((69, 36), (18, 36))

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [12]:
from sklearn.neural_network import MLPClassifier

model = MLPClassifier(
    hidden_layer_sizes=(20,10),
    learning_rate_init=0.001,
    max_iter=500,
    random_state=42
)

model.fit(X_train_scaled, y_train)

MLPClassifier(hidden_layer_sizes=(20, 10), max_iter=500, random_state=42)

In [13]:
from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test_scaled)

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.8333333333333334

In [14]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(
    model,
    scaler.fit_transform(X),
    y,
    cv=5
)

scores

array([0.77777778, 0.88888889, 0.70588235, 0.82352941, 0.64705882])

In [15]:
model = MLPClassifier(
    hidden_layer_sizes=(10,),
    learning_rate_init=0.001,
    max_iter=300,
    random_state=42
)

scores = cross_val_score(model, scaler.fit_transform(X), y, cv=5)
scores.mean()

c:\Users\whimp\anaconda3\envs\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\whimp\anaconda3\envs\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\whimp\anaconda3\envs\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\whimp\anaconda3\envs\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(
c:\Users\whimp\anaconda3\envs\myenv\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (300) reached and the optimization hasn't converged yet.
  warnings.warn(

np.float64(0.7104575163398693)

In [16]:
model = MLPClassifier(
    hidden_layer_sizes=(30,15),
    learning_rate_init=0.005,
    max_iter=1000,
    random_state=42
)

scores = cross_val_score(model, scaler.fit_transform(X), y, cv=5)
scores.mean()

np.float64(0.7346405228758169)

Four different hyperparameter combinations were tested for the neural network model using 5-fold cross validation. The configuration with hidden layers (20,10) produced the highest average accuracy among the tested models. Increasing the network size to (30,15) did not outperform this configuration and produced slightly lower accuracy. This may be due to the relatively small dataset size (87 samples), which can limit the benefits of larger neural networks. Overall, increasing model complexity did not consistently improve performance.